import React, { PropTypes, Component, } from 'react'
import RaisedButton from 'material-ui/lib/raised-button'
import FontIcon from 'material-ui/lib/font-icon'

import moment from 'moment'

import { MainColors, } from '../theme'

const styles = {
  footer: {
    backgroundColor: MainColors[3],
    color: MainColors[2],
    borderTop: '1px solid rgba(0, 0, 0, 0.05)',
  },

  aboutProfile: {
    title: {
      fontSize: 24,
      fontWeight: 500,
      marginLeft: '0px',
    },

  },

  copyright: {
    container: {
      backgroundColor: MainColors[2],
    },

    rightLinkText: {
      fontWeight: 400,
      fontStyle: 'italic',
      color: MainColors[3],
    },

    leftTextUserId: {
      fontWeight: 500,
      fontStyle: 'italic',
      color: MainColors[3],
    },
  },

}

// TODO: 3. converts tab content color to grey

class Footer extends Component {

  renderAboutProfile(meta) {

    let aboutProfileText = null
    const collectedAts = meta.schema_collected_ats

    /** if schema_collceted_ats is empty, use created_at */
    if (collectedAts === void 0 || collectedAts.length === 0) {
      const since = moment(meta.schema_created_at).fromNow()
      aboutProfileText = `Created ${since}`
    } else {
      const since = moment(collectedAts[collectedAts.length - 1]).fromNow()
      aboutProfileText = `Updated ${since} (${collectedAts.length} times)`
    }

    return (
      <div className='container'>
        <div className='row'>
          <div className='col s12 l6'>
            <h5 className='' style={styles.aboutProfile.title}>About Profile</h5>
            <p className=''>{aboutProfileText}</p>
            <RaisedButton
              className='blue-grey darken-1' secondary
              linkButton target='_blank'
              href={`https://github.com/${meta.github_user}/${meta.github_repository}`}
              label='Github Link' icon={<FontIcon className='fa fa-github' />}
              />
          </div>
          <div className='col s12 l4 offset-l2'>
          </div>
        </div>
      </div>
    )
  }

  renderCopyright(user) {
    return (
      <div className='footer-copyright' style={styles.copyright.container}>
        <div className='container'>
          <span>Copyright © 2016</span>
          <span style={styles.copyright.leftTextUserId}> {user.login}, </span>
          <span> All rights reserved.</span>
          <div className='right'>
            <span>generated by </span>
            <a href='https://github.com/oh-my-github/generator'
               style={styles.copyright.rightLinkText}>
              oh-my-github
            </a>
          </div>
        </div>
      </div>
    )
  }

  render() {
    const { user, meta, } = this.props

    return (
      <footer className='page-footer' style={styles.footer}>
        {this.renderAboutProfile(meta)}
        {this.renderCopyright(user)}
      </footer>
    )
  }
}

export default Footer

Footer.propTypes = {
  user: PropTypes.object.isRequired,
  meta: PropTypes.object.isRequired,
}
